# Generated by Django 3.2.14 on 2022-08-31 12:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=128)),
                ('issue_number', models.PositiveIntegerField(help_text='Used as a slug for each issue', unique=True)),
                ('publish_date', models.DateTimeField()),
                ('issue_type', models.CharField(choices=[('1', 'Daily Issue'), ('2', 'Weekly Issue'), ('4', 'Weekly Issue')], default='2', max_length=2)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('is_draft', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-publish_date', '-issue_number'],
            },
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Post categories',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verified', models.BooleanField(default=False)),
                ('subscribed', models.BooleanField(default=False)),
                ('verification_sent_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('source_url', models.URLField()),
                ('is_visible', models.BooleanField(default=False)),
                ('short_description', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='newsfeed.postcategory')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='newsfeed.issue')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('subject', models.CharField(max_length=128)),
                ('is_sent', models.BooleanField(default=False)),
                ('schedule', models.DateTimeField(blank=True, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newsletters', to='newsfeed.issue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
