# Generated by Django 4.1.1 on 2022-11-27 18:00
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0003_newsletter"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_address", models.EmailField(max_length=254, unique=True)),
                ("token", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("verified", models.BooleanField(default=False)),
                ("subscribed", models.BooleanField(default=False)),
                ("verification_sent_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
