# Generated by Django 4.0.6 on 2022-08-26 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0003_alter_issue_issue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_type',
            field=models.IntegerField(choices=[('1', 'Daily Issue'), ('2', 'Weekly Issue'), ('4', 'Weekly Issue')], default=2),
        ),
    ]
