# Generated by Django 4.1.1 on 2022-11-27 18:04
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("newsfeed", "0004_subscriber"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="issue",
            index=models.Index(
                fields=["publish_date", "issue_number"],
                name="newsfeed_is_publish_ce2043_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="newsletter",
            index=models.Index(
                fields=["-schedule"], name="newsfeed_ne_schedul_a61f24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["issue", "category", "order", "-created_at"],
                name="newsfeed_po_issue_i_0df828_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="postcategory",
            index=models.Index(fields=["order"], name="newsfeed_po_order_bd5355_idx"),
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(
                fields=["-created_at"], name="newsfeed_su_created_bd1997_idx"
            ),
        ),
    ]
